### ISSUE TITLE
at_c: use size_t where unsigned long is and stdbool for booleans

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#105]
Would like a discussion of making C99 our minimum C version (because stdbool is only supported in C99+). This would mean dropping support for ANSI C (C89/90).

The sprint points allocated to this ticket will consider two things:
1. going in and replacing `unsigned long` with `size_t` from the `stddef.h` header
2. converting from int to booleans (such as iscached and ispublic in metadata) using `bool` in `stdbool.h`
3. Update documentation to say that the minimum version is C99

Another interesting thing to note about using type headers is it guarantees the size of the type. Example: a int may be 8 bytes in some systems as opposed to the regular 4, but using something like `uint64_t` from `stdint.h` guarantees it to be 8 bytes all the time.

**Comment by JeremyTubongbanua** [comment]
@XavierChanth @cpswan Would like your input on making C99 our minimum required version. 

[mbedtls](https://github.com/Mbed-TLS/mbedtls) has their minimum version as C99.

**Comment by cpswan** [comment]
I'm OK with us doing this, but I think we need to explain WHY? This may even justify an architecture decision record (ADR).

For mbedtls I'm very comfortable with it being our default. But I think from the beginning we wanted 'batteries included but removable' so that if customers had another TLS library it wouldn't be too much upheaval to switch. Any decision regarding C99 should probably align with ensuring we don't close off options there.

**Comment by xavierchanth** [comment]
There are plenty of useful features and data types added in C99, and it seems to be the baseline for support because of this, many useful data types, static keyword, snprintf for string construction, etc.

If we need to support <C99 later, we can look at doing so, but we reduce time to market trying to do so now.

**Comment by JeremyTubongbanua** [comment]
If this decision document is approved, I will go ahead with refactors.

https://github.com/atsign-foundation/at_protocol/pull/134

**Comment by xavierchanth** [comment]
https://github.com/atsign-foundation/at_protocol/pull/134 is approved by me. I think we should go ahead with C99. No reason to make things more difficult unless absolutely necessary.
