### ISSUE TITLE
at_c: notifications should support non-ascii values

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#259]
currently, notifiy_params holds `char *value`,

But we should be able to support notifications that send bytes as well, instead of just strings.

This PR should do the following:

- [ ] Change function header to accept `unsigned char *value, size_t valuelen`
- [ ] Add a test for sending notification bytes

**Comment by cpswan** [comment]
The notify verb specifies a base64 payload https://github.com/atsign-foundation/at_protocol/blob/trunk/specification/at_protocol_specification.md#the-notify-verb

So is the intent here to take binary input and seamlessly encode it?

👀 @gkc @XavierChanth

**Comment by JeremyTubongbanua** [comment]
> So is the intent here to take binary input and seamlessly encode it?

Yes, but now that I hear it said out loud, it may not be worth doing. Simply telling the caller that it has to be ASCII could simplify a lot of confusion

**Comment by xavierchanth** [comment]
> The notify verb specifies a base64 payload https://github.com/atsign-foundation/at_protocol/blob/trunk/specification/at_protocol_specification.md#the-notify-verb
> 
> So is the intent here to take binary input and seamlessly encode it?
> 
> 👀 @gkc @XavierChanth

The spec is also missing information about what happens when the notification metadata includes isEncrypted:false, since the implicit default is isEncrypted:true (also unspecified). The spec assumes the notification is encrypted and we always base64 encode the cyphertext before transmitting. But we typically don't base64 encode unencrypted text.

I think it is time to do a review of the spec, and start filling in the gaps, especially around notify.

**Comment by JeremyTubongbanua** [comment]
If someone still wants to send a non-ascii non-encrypted notification, we should just keep it simple and enforce it to be ascii, so that we don't go into base64 encoding things twice unnecessarily
